apiVersion: v1
kind: Service
metadata:
  name: workwave
  labels:
    app: workwave
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: workwave
  type: NodePort